import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/storeProvider";
import { Toaster } from "sonner";
import ClientWrapper from "@/components/features2/ClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web Grocery App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ClientWrapper>{children}</ClientWrapper>{" "}
          {/* ✅ logic client pindah ke sini */}
        </StoreProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
