import "dotenv/config";

export const {
  PORT,
  FE_URL,
  API_KEY,
  GOOGLE_CLIENT_ID,
  JWT_SECRET,
  NODEMAILER_USER,
  NODEMAILER_PASS,
  CLOUDINARY_NAME,
  CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
  REDIS_URL,
  RAJAONGKIR_BASE_URL,
  RAJAONGKIR_API_KEY
} = process.env;
