export * from "./productAdmin.interface";
export * from "./branch"
export * from "./product.interface"
export * from "./user.interface";
export * from "./inventory";
export * from "./discount";
export * from "./report";
export * from "./store.interface";
export * from "./category"